services:
  - type: web
    name: chat-app-backend
    env: node
    rootDir: fullstack-chat-app/backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: chat-app-frontend
    env: node
    rootDir: fullstack-chat-app/frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://chat-app-backend.onrender.com
      - key: NODE_ENV
        value: production 